### ISSUE TITLE
Invalid syntax on line 871

### ISSUE THREAD

**Issue by TLMcNulty** [SpringerPE/diamond-ontapclustercollector#4]
I'm not a python guy, but I've been working on setting up a netapp - graphite - grafana chain and it's displaying metrics from the system this is running in, not the target appliance. Maybe it's because the ontapng.py doesn't compile?

SyntaxError: ('invalid syntax', ('ontapng.py', 871, 31, '                            for item in head.children_get()\n'))

**Comment by TLMcNulty** [comment]
Am I missing a dependency?

**Comment by jriguera** [comment]
Let me have a look

**Comment by jriguera** [comment]
Hi @TLMcNulty, I will update the repo this week, meanwhile just remove this function:  `def _decode_elements2dict(self, head, filter=None):`  and it will work with diamond.

**Comment by TLMcNulty** [comment]
Thanks man. Really appreciate the time you took.

**Comment by jriguera** [comment]
@TLMcNulty closed, new version
